export const VIETNAM_BANKS = [
  { code: 'VCB', name: 'Vietcombank', shortName: 'Vietcombank' },
  { code: 'TCB', name: 'Techcombank', shortName: 'Techcombank' },
  { code: 'MB', name: 'MB Bank', shortName: 'MB' },
  { code: 'VPB', name: 'VPBank', shortName: 'VPBank' },
  { code: 'ACB', name: 'ACB', shortName: 'ACB' },
  { code: 'BIDV', name: 'BIDV', shortName: 'BIDV' },
  { code: 'CTG', name: 'VietinBank', shortName: 'VietinBank' },
  { code: 'STB', name: 'Sacombank', shortName: 'Sacombank' },
  { code: 'VIB', name: 'VIB', shortName: 'VIB' },
  { code: 'TPB', name: 'TPBank', shortName: 'TPBank' },
  { code: 'HDB', name: 'HDBank', shortName: 'HDBank' },
  { code: 'MSB', name: 'MSB', shortName: 'MSB' },
  { code: 'OCB', name: 'OCB', shortName: 'OCB' },
  { code: 'SHB', name: 'SHB', shortName: 'SHB' },
  { code: 'SSB', name: 'SeABank', shortName: 'SeABank' },
  { code: 'LPB', name: 'LienVietPostBank', shortName: 'LPBank' },
  { code: 'EIB', name: 'Eximbank', shortName: 'Eximbank' },
  { code: 'VCCB', name: 'VietCapital Bank', shortName: 'VietCapital' },
];
